server:
  port: 8080
  servlet:
    contextPath: /transformersbattle

#In memory data store configuration
spring:
  datasource:
    url: jdbc:h2:mem:transformerdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2db
